- Example_Systems/SmallNewEngland/OneZone/Settings/genx_settings.yml
- src/write_outputs/dftranspose.jl
Speeds up and reduces memory requirement of dftranspose.
Tested on the SmallNewEngland example cases and returned the same CSV files. Saw at least a 10x speedup and reduction in memory usage during the output writes. Separately tested on larger results and memory improvements appeared to increase.
Tested using the current JuliaGenXEnv modules, in particular DataFrames v0.20.2. Later versions may require a rewrite, but will also allow more flexibility in how the tranpose handles ordering or other issues.
Changes to genx_settings.yml can be rejected. Just Windows vs Mac setting.
> dftranspose speedup

- src/write_outputs/write_costs.jl
Added condition in response one issue on github to check for whether storage is present or not when adding the term eTotalCVarIn to the total variable cost in write_costs.jl
> Missing eTotalCVarIn w/o storage

- Project.toml
The Project.toml GenX version was set at 1.0.0. This PR corrects it to version 0.1.0 according to the latest release.
> Corrected the GenX version in Project.toml to 0.1.0

- docs/src/data_documentation.md
In the `Example_Systems`, a lack of fuel requirements for a resource is referenced as `None`, not `none` in `Fuels_data.csv` and `Generators_data.csv`. The columns are case-sensitive so this matters. This fixes the typo in the documentation.
> Correct 'none' to 'None' in doc of Fuels_data

- docs/src/model_notation.md
Sets (capital letters) are subsets (\subseteq) of other sets. Elements (lowercase letters ) are \in sets.
> Correct model_notation: \in to \subseteq; acryonym definitions

- Example_Systems/RealSystemExample/ISONE_Singlezone/Run.jl
- Example_Systems/RealSystemExample/ISONE_Trizone/Run.jl
- Example_Systems/RealSystemExample/ISONE_Trizone_FullTimeseries/Run.jl
- Example_Systems/RealSystemExample/MGA_ISONE_Trizone_FullTimeseries/Run.jl
- Example_Systems/SmallNewEngland/OneZone/Run.jl
- Example_Systems/SmallNewEngland/OneZone_3VREBin/Run.jl
- Example_Systems/SmallNewEngland/ThreeZones/Run.jl
In all the example Run.jl scripts, the line myinputs = Dict() did nothing because it is immediately
overwritten on the next line by the load_inputs function. This simplifies the scripts and reduces possible confusion as to why the line is there.
This addresses #71 .
> Simpify run scripts

- .gitignore
I saw that this (empty) output file was in the base directory. It should be removed and files of this name should in general be ignored.
This fixes #87 .
> Add cplex.log file to gitignore.

- src/additional_tools/method_of_morris.jl
Here's a few improvements to the Morris script. I made them in an attempt to better understand the code in preparation for my own improvements.
Improvements include
* deduplicating code by using a `Dict` relating the file that a column is in and the name of the dataframe.
* breaking up long repeated lines into shorter expressions to increase readability
* making a O(n^2) algorithm more like O(n) (though this is admittedly not performance critical)
* substituting `joinpath` for custom directory forming
* replace a for loop with builtin `cumsum` for readability
* replace `eltype(x)[]` with `similar(x, 0)` which I think is better semantically?
* replace `df[!, :col][1]` with `df[1, :col]` for brevity and less syntax
I tested before-and-after these two commits against the FLECCS example with …
> A few improvements to the morris script

- src/additional_tools/method_of_morris.jl
This allows the user to have a much simpler Method of Morris input
script. It's no longer necessary to include lines for every generator
for every parameter, if these lines would otherwise be 0 Upper_bound, 0
Lower_bound, 1 p_steps.
> Add scripts to replace missing values in Morris

- Example_Systems/FLECCSExample/USSingleRegion_CarbonTax300/Settings/genx_settings.yml
- Example_Systems/SmallNewEngland/OneZone/Settings/genx_settings.yml
- Example_Systems/SmallNewEngland/OneZone_3VREBin/Settings/genx_settings.yml
- src/configure_settings/configure_settings.jl
- src/load_inputs/load_generators_data.jl
- src/model/generate_model.jl
- src/model/resources/storage/storage.jl
This prevents errors when the obsolete LongDurationStorage key is not included in
settings.
(This is a cherry-pick from the `removeLDSKey` branch which currently has an open PR to `Dev`.)
Some of the example settings have changed so I'd request review there.
> Remove references to LongDurationStorage key

- src/load_inputs/load_inputs.jl
Splitting this into functions makes the very long line easier to read.
It also provides a place where the smaller functions can be modified without
affecting the main function. This may be the case if, say, there is a
new resource type which is not in STOR_LONG_DURATION but nevertheless
has LDS-like capabilities which need the Period_Map.
> Refactor period map loading logic

- src/load_inputs/load_cap_reserve_margin.jl
The `dfTransCapRes` matrix created using CapRes_ columns isn't used anywhere in GenX. Remove those lines so the CapRes_ cols aren't required in Network.csv.
> Remove unused code requiring CapRes_* cols

- src/write_outputs/write_outputs.jl
A simple rearrangement ensures that `write_costs` is called only once. This addresses #135 .
> Call write_costs exactly once

- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Inputs/Inputs_p1/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Inputs/Inputs_p2/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Inputs/Inputs_p3/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Settings/multi_stage_settings.yml
- src/multi_stage/load_inputs_multi_stage/configure_multi_stage_inputs.jl
- src/multi_stage/model_multi_stage/transmission_multi_stage.jl
These changes resolve two bugs with regard to network expansion in multi-stage GenX. First, network expansion in any given stage was limited only by the cumulative maximum flow (Line_Max_Flow_Possible_MW) and not also the single-stage maximum reinforcement (Line_Max_Reinforcement_MW) as had been intended. Second, the sets of expandable and non-expandable lines were defined improperly for stages after the first leading to all subsequent stages being denied network expansion. This pull request resolves these two issues by (1) defining a single-stage maximum reinforcement constraint in transmission_multi_stage.jl just like that in transmission.jl for single-stage GenX, and (2) redefining the EXPANSION_LINES set in configure_multi_stage_inputs.jl to reflect the inputs as intended. 
For the …
> Resolving first-stage-only network expansion issue in multi-stage GenX

- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Run_multi_stage.jl
- src/multi_stage/dual_dynamic_programming.jl
- src/multi_stage/load_inputs_multi_stage/configure_multi_stage_inputs.jl
- src/multi_stage/model_multi_stage/investment_multi_stage.jl
- src/multi_stage/model_multi_stage/transmission_multi_stage.jl
To annualize costs in the myopic case, we no longer overwrite the originally annualized input costs with overnight capital costs, we do not apply the discount factor DF (used to translate costs to net present costs) to the objective, and we do not apply the O&M multiplier OPEXMULT (to scale yearly O&M costs to account for the full duration between model stages). We now define OPEXMULT in one location (configure_multi_stage_inputs) in order to prevent recalculations in several different locations which might result in errors when making future changes, but this does require passing the input dictionary (which houses OPEXMULT) to the write_costs() and initialize_cost_to_go() functions where it had not been passed previously.
> Annualizing costs in myopic multi-stage GenX

- src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
- src/write_outputs/write_charging_cost.jl
- src/write_outputs/write_energy_revenue.jl
- src/write_outputs/write_outputs.jl
This vectorizes ChargingCost, EnergyRevenue, and ReserveMarignRevenue. These were tested on the ISONE_Trizone example and the results should be exactly identical (except for with additional floating point digits).
These changes are copied from those of Qingyu but slightly edited to keep outputs as similar as possible.
> Vectorize the three slowest outputs

- src/write_outputs/reserves/write_reg.jl
- src/write_outputs/reserves/write_rsv.jl
- src/write_outputs/transmission/write_transmission_flows.jl
- src/write_outputs/transmission/write_transmission_losses.jl
- src/write_outputs/ucommit/write_shutdown.jl
- src/write_outputs/ucommit/write_start.jl
The period weighting ω is now taken into account for sums of reg and rsv
values, starts and shutdowns.
Co-authored-by: Qingyu Xu <xuqingyu0610@gmail.com>
> Annualize outputs for reserves and ucommit

- docs/src/multi_stage_model_overview.md
Multi-stage GenX markdown documentation (multi_stage_model_overview.md) shows incorrect field names ("Retirement" instead of "Retired") for three Generators_data.csv fields. This updates the documentation to match.
> DDP Documentation Fix

- Example_Systems/SmallNewEngland/OneZone_MultiStage/Inputs/Generators_data_multi_period_deprecated.csv
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Run_multi_stage.jl
- src/time_domain_reduction/time_domain_reduction.jl
The parse_multi_stage_data() function in TDR previously iterated over the wrong dimension, resulting in errors for most examples that do not meet certain specifications (e.g., SmallNewEngland/OneZone_MultiStage) but functioning correctly in others (e.g., ThreeZones_MultiStage). Testing shows that this small fix works for both OneZone and ThreeZones.
> Correcting multi-stage TDR indexing error

- src/load_inputs/load_generators_data.jl
Asymmetric storage is currently excluded from LDS/non-LDS sets. This leads to error (if any LDS is included) where STOR=2 technologies do not get state of charge constraints.
> Include STOR=2 techs in STOR_LONG_DURATION and STOR_SHORT_DURATION sets

- src/model/resources/thermal/thermal_commit.jl
The min-uptime and min-downtime constraints can be greatly simplified
using a bit of modular arithmetic. This also corrects some off-by-one
errors in the previous implementation, and changes the definition of
Up_Time to be (previous Up_Time) - 1.
Previously Up_Time = 1 meant a generator would need to be on for *two*
hours (except for some edge case bugs that resulted in either 1 or 3
hours), now it's uniformly one hour as expected.
This fixes #150 and is an alternative (plus additional fixes) of #149 .
> Fix and simplify Up&Down_Time constraints

- src/load_inputs/load_generators_data.jl
This prevents Hydro_Energy_to_Power_Ratio from being accessed if there are no HYDRO generators. This means that Generators_data can be simpler in cases with no hydro.
> Gate for accessing Hydro_Energy_to_Power_Ratio

- Example_Systems/SmallNewEngland/OneZone_MultiStage/Run_multi_stage.jl
- src/multi_stage/dual_dynamic_programming.jl
We identified an error in the current version of DDP where starting capacities in one stage were not guaranteed to be equal to the end capacities in the previous stage. This was due to the backward pass overwriting forward pass model results. While we develop a more sustainable formulation that does not require this extra runtime, this change adds a final forward pass after successful convergence guaranteeing both feasibility and convergence criteria. Tests have shown that the inter-stage capacity mismatches have been corrected by this change.
> DDP Post-convergence extra forward pass

- src/write_outputs/write_costs.jl
This ensures that the zonal cost subtotals include non-served energy and
the charging- and energycap- related fixed costs of storage resources.
This addresses #63 .
> Fix zonal cost summations

- src/additional_tools/method_of_morris_parallel_v0.jl
- src/additional_tools/method_of_morris_v0.jl
- src/additional_tools/method_of_morris_v1.jl
- src/additional_tools/method_of_morris_v2.jl
- src/load_inputs/load_inputs.jl
- src/multi_stage/dual_dynamic_programming.jl
- src/multi_stage/write_settings.jl
- src/time_domain_reduction/time_domain_reduction.jl
- src/write_outputs/capacity_reserve_margin/write_capacity_value.jl
- src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
- src/write_outputs/reserves/write_rsv.jl
- src/write_outputs/transmission/write_transmission_flows.jl
- src/write_outputs/transmission/write_transmission_losses.jl
- src/write_outputs/write_charging_cost.jl
- src/write_outputs/write_energy_revenue.jl
- src/write_outputs/write_nse.jl
- src/write_outputs/write_outputs.jl
- src/write_outputs/write_power.jl
- src/write_outputs/write_power_balance.jl
This simplifies functions by removing the unneeded 'sep' argument and by using the julia builtin `joinpath` to construct paths with appropriate directory separators.
> Use joinpath rather than manual path construction from strings

- src/additional_tools/modeling_to_generate_alternatives.jl
- src/load_inputs/load_generators_data.jl
- src/load_inputs/load_reserves.jl
- src/model/core/discharge/discharge.jl
- src/model/core/discharge/investment_discharge.jl
- src/model/core/emissions.jl
- src/model/core/reserves.jl
- src/model/policies/cap_reserve_margin.jl
- src/model/resources/curtailable_variable_renewable/curtailable_variable_renewable.jl
- src/model/resources/hydro/hydro_inter_period_linkage.jl
- src/model/resources/hydro/hydro_res.jl
- src/model/resources/must_run/must_run.jl
- src/model/resources/storage/investment_charge.jl
- src/model/resources/storage/investment_energy.jl
- src/model/resources/storage/long_duration_storage.jl
- src/model/resources/storage/storage.jl
- src/model/resources/storage/storage_all.jl
- src/model/resources/thermal/thermal_commit.jl
- src/model/resources/thermal/thermal_no_commit.jl
Two types of simplfications have been mode. First,
df[!, :x][y] -> df[y , :x]
Second,
df[a, :][:, :R_ID] -> df[a, :R_ID]
These may save some memory and time, but more importantly make the code easier to read. This should in turn make it easier to make changes and spot any errors.
> Simplify dataframe accesses

- src/write_outputs/write_reliability.jl
reliabilty -> reliability
Note: this may break automated analysis scripts.
> Fix spelling of output file, now reliability.csv

- .travis.yml
Disabled until tests are run locally on Julia 1.7.x,1.8.x, and 1.9.x and debugged in order to prevent failures on codes that should run without any problem on Julia 1.6.x
> Disabled CI and builds on Julia nightly

- Example_Systems/MethodofMorrisExample/OneZone/Run.jl
- Example_Systems/MethodofMorrisExample/OneZone/Settings/time_domain_reduction_settings.yml
- Example_Systems/RealSystemExample/ISONE_Singlezone/Run.jl
- Example_Systems/RealSystemExample/ISONE_Trizone/Run.jl
- Example_Systems/RealSystemExample/ISONE_Trizone_FullTimeseries/Run.jl
- Example_Systems/RealSystemExample/ISONE_Trizone_FullTimeseries/Settings/time_domain_reduction_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Run.jl
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Run_multi_stage.jl
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Settings/time_domain_reduction_settings.yml
- Example_Systems/RealSystemExample/MGA_ISONE_Trizone_FullTimeseries/Run.jl
- Example_Systems/RealSystemExample/MGA_ISONE_Trizone_FullTimeseries/Settings/time_domain_reduction_settings.yml
- Example_Systems/SmallNewEngland/OneZone/Run.jl
- Example_Systems/SmallNewEngland/OneZone/Settings/time_domain_reduction_settings.yml
- Example_Systems/SmallNewEngland/OneZone_3VREBin/Run.jl
- Example_Systems/SmallNewEngland/OneZone_3VREBin/Settings/time_domain_reduction_settings.yml
- Example_Systems/SmallNewEngland/OneZone_MultiStage/Run_multi_stage.jl
- Example_Systems/SmallNewEngland/OneZone_MultiStage/Settings/time_domain_reduction_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones/Run.jl
- Example_Systems/SmallNewEngland/ThreeZones/Settings/time_domain_reduction_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Run_multi_stage.jl
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Settings/time_domain_reduction_settings.yml
- src/time_domain_reduction/time_domain_reduction.jl
This pull request includes one functional change and one bug fix. Before this request, multi-stage time domain reduction would concatenate the input data of all stages, run one TDR operation for the whole set, and distribute TDR outputs to each stage directory accordingly. This pull request allows the user to instead run TDR for each stage individually using the setting MultiStageConcatenate=0 in time_domain_reduction_settings.yml. Additionally, an aliasing issue led to improper parameter scaling behavior under some settings. This pull request fixes this issue by creating a copy of the settings dictionary. Changes to the run files and settings files are applied to each example in the examples directory.
> Multi-stage TDR update with parameter scaling fix

- src/load_inputs/load_generators_data.jl
To make sure that files that do not have RETRO column in the Generators_data.csv are read error free by creating a dummy RETRO column for them with all zero entries
> load_generator_data modification

- docs/src/how_to_run_genx.md
Fix path to image assets.
This is a relative path, and is shorter by one `docs/assets/src` than the path in the main README.
> Fix images in how_to_run_genx.md

- src/multi_stage/dual_dynamic_programming.jl
`getdual` and `getvalue` were deprecated. This replaces the calls with `dual` and `value`.
> Fix JuMP interface in DPP

- README.md
- docs/src/how_to_run_genx.md
Auto-populated MUMPS_seq_jll v5.5.1 dependency causes pre-compilation issues with Ipopt_jll, Clp_jll, SCIP_jll, Cgl_jll, Cbc_jll, SCIP, Clp, Cbc, GenX on Windows.
'ERROR: LoadError: InitError: could not load library'
Edited run instructions to downgrade MUMPS_seq_jll to v5.4.1 after instantiate.
> Updated instructions for MUMPS_seq_jll error

- src/model/resources/storage/investment_charge.jl
GenX doesn't currently respect the eTotalCapCharge  < Max_Charge_Cap_MW constraint. I've been shown cases where an asymmetric storage technology has the correct max discharge capacity and energy capacity, but not charge capacity.
I'm pretty sure it's because of this indexing error. It doesn't match any of the other indexing for similar constraints. Currently waiting on longer tests to confirm the fix.
> Fix indexing in setting eTotalCapCharge max and min

- src/GenX.jl
- src/multi_stage/dual_dynamic_programming.jl
This PR attempts to fix writing of different multi-stage outputs by mentioning the relevant files in GenX.jl and accounting for network expansion
> Fix multistage DDP bug for output writing

- src/model/core/ucommit.jl
This PR attempts to modify the startup cost formulation in commit.jl to reflect the variation with the hours. Instead of the original formulation:
`@expression(EP, eCStart[y in COMMIT, t=1:T],(inputs["omega"][t]*inputs["C_Start"][y]*vSTART[y,t]))`
it's now written as
`@expression(EP, eCStart[y in COMMIT, t=1:T],(inputs["omega"][t]*inputs["C_Start"][y,t]*vSTART[y,t]))`
And the doctoring has also been adjusted.
> Time Varying Startup Cost

- src/model/resources/storage/storage_all.jl
This PR addresses error flagged in Issue #280. Constraints that limit max charge/discharge rates with or without reserves based on available energy storage capacity did not account for charge or discharge efficiencies. This is corrected here.
> Addressing issue #280

- docs/src/data_documentation.md
- src/load_inputs/load_network_data.jl
The network map can now be loaded from columns
```
Network_Lines, Origin_Zone, Destination_Zone
1, 1, 2
2, 1, 3
```
in addition to still supporting the direct matrix format,
```
Network_Lines, z1, z2, z3
1, 1, -1, 0
2, 1, 0, -1
```
> Add zone list interface for loading the network map

- src/GenX.jl
- src/load_inputs/load_cap_reserve_margin.jl
- src/load_inputs/load_co2_cap.jl
- src/load_inputs/load_dataframe.jl
- src/load_inputs/load_energy_share_requirement.jl
- src/load_inputs/load_fuels_data.jl
- src/load_inputs/load_generators_data.jl
- src/load_inputs/load_generators_variability.jl
- src/load_inputs/load_inputs.jl
- src/load_inputs/load_load_data.jl
- src/load_inputs/load_minimum_capacity_requirement.jl
- src/load_inputs/load_network_data.jl
- src/load_inputs/load_period_map.jl
- src/load_inputs/load_reserves.jl
- src/multi_stage/write_multi_stage_capacities_charge.jl
- src/multi_stage/write_multi_stage_capacities_discharge.jl
- src/multi_stage/write_multi_stage_capacities_energy.jl
- src/multi_stage/write_multi_stage_costs.jl
- src/multi_stage/write_multi_stage_network_expansion.jl
- src/time_domain_reduction/time_domain_reduction.jl
Add a function to load a dataframe from our common sort of CSV file. This helps DRY with regard to dataframe loading settings, making code easier to read and ensuring the same options (header=1, copycols=false) are applied everywhere. Also, if we want to make dataframe loading smarter, now there's one centralized place to do it.
This commit also adds a feature that CSV files of different case can also be loaded, addressing #288 . It does not look for folders or yaml files with different cases. @RuaridhMacd it would be great if you could test this on a case-insensitive file system. 
The current implementation is sort of a minimum-working-example, it could certainly be better.
> Functionalize Dataframe loading from csv

- src/load_inputs/load_cap_reserve_margin.jl
- src/load_inputs/load_co2_cap.jl
- src/load_inputs/load_dataframe.jl
- src/load_inputs/load_energy_share_requirement.jl
This allows sets of columns to be extracted from a dataframe into a matrix, for columns which are in any order. Previously the columns needed to be consecutive and in order.
For example, the ESR_1, ESR_2, ... ESR_N columns in Energy_share_requirement.csv can now be provided in any order.
> Add function for extracting matrix from a df

- src/write_outputs/write_emissions.jl
Removes division by ModelScalingFacroe when ParameterScale is set to 0, to express the COR emissions in tons (instead of kilotons).
> Correct scaling for CO2 Emissions

- src/GenX.jl
- src/model/resources/flexible_demand/flexible_demand.jl
- src/model/resources/hydro/hydro_res.jl
- src/model/resources/storage/storage_all.jl
- src/model/resources/thermal/thermal_commit.jl
- src/model/resources/thermal/thermal_no_commit.jl
- src/model/utility.jl
These commits clean up several pairs of constraints, unifying them by using `hoursbefore`, which has been moved to a new `utility.jl` file for general utility functions.
Although resulting formulation should be mathematically identical (and I'd appreciate a reviewer to verify this!) in practice, since the constraints are now in a different order, solvers will find a slightly different solution.
> Deduplicate constraints

- src/model/generate_model.jl
This PR modifies the generate_model.jl file by changing the following line of code:
co2_cap!(EP, inputs, setup)
to
if setup["CO2Cap"] >= 1
co2_cap!(EP, inputs, setup)
end
This is essential because if CO2 capacity constraints are not taken into consideration, then we don't need to execute the co2_cap!(EP, inputs, setup) function.
> CO2 Cap Condition check

- src/model/resources/thermal/thermal_commit.jl
Currently there's a mismatch between the implementation in the code base and the doc pages regarding the minimum up time and down time. This PR fixes the documentation by starting the summation counter as $$ vCOMMIT[t] \geq \sum_{s = t-(MinUpTime-1)}^t vSTART[s]$$ instead of the $$ vCOMMIT[t] \geq \sum_{s = t-MinUpTime}^t vSTART[s]$$
> Correcting the minimum up & down times in doc page

- src/model/resources/storage/investment_energy.jl
- src/model/resources/storage/storage_all.jl
Removed the constraints
[y in STOR_ALL], EP[:eTotalCapEnergy][y] >= dfGen[y,:Min_Duration] * EP[:eTotalCap][y]
[y in STOR_ALL], EP[:eTotalCapEnergy][y] <= dfGen[y,:Max_Duration] * EP[:eTotalCap][y]
from storage_all.jl to investment_energy.jl
> Move constraints pertaining to investment

- src/configure_settings/configure_settings.jl
- src/model/resources/hydro/hydro_res.jl
- src/model/resources/storage/storage.jl
- src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
- src/write_outputs/capacity_reserve_margin/write_reserve_margin_w.jl
This is a temporary reversion to fix divide-by-zero errors and a flawed overall formulation. A future PR will introduce more comprehensive CapRes contributions for storage resources.
> Revert cap res period length

- src/model/resources/hydro/hydro_res.jl
- src/model/resources/thermal/thermal_commit.jl
This PR attempts to correct the ramping constraints for thermal and hydro generators by introducing the reserve and regulation terms in the respective constraints and by changing 
#rampup constraint
@constraint(EP,[y in THERM_COMMIT, t in 1:T],
EP[:vP][y,t]-EP[:vP][y, hoursbefore(p, t, 1)] <= dfGen[y,:Ramp_Up_Percentage]*dfGen[y,:Cap_Size]*(EP[:vCOMMIT][y,t]-EP[:vSTART][y,t])
+ min(inputs["pP_Max"][y,t],max(dfGen[y,:Min_Power],dfGen[y,:Ramp_Up_Percentage]))*dfGen[y,:Cap_Size]*EP[:vSTART][y,t]
- dfGen[y,:Min_Power]*dfGen[y,:Cap_Size]*EP[:vSHUT][y,t])
@constraint(EP,[y in THERM_COMMIT, t in 1:T],
EP[:vP][y, hoursbefore(p, t, 1)]-EP[:vP][y,t] <= dfGen[y,:Ramp_Dn_Percentage]*dfGen[y,:Cap_Size]*(EP[:vCOMMIT][y,t]-EP[:vSTART][y,t])
- dfGen[y,:Min_Power]*dfGen[y,:Cap_Size]*EP[:vSTART][y,t]
+ …
> Inclusion of Reserve and Regulation in ramp limits

- src/model/resources/hydro/hydro_res.jl
- src/model/resources/thermal/thermal_commit.jl
A recent change to the THERM_COMMIT ramp expessions added calls to :vREG and :vRSV variables. However, these variables did not exist at all unless setup["Reserves"] > 1; and further they would only exist for a subset of the thermal generators. This would throw an error whenever Reserves was not 1 or if not all thermal generators with committment had positive Reg_Max and sv_Max entries.
This change introduces expressions that are defined for all generators y in THERM_COMMIT, which are 0 if Reserves are off and reference the vREG and vRSV variables for the correct generators if Reserves are on.
This lets us modify the ramp expression to include these reserve and regulation terms, while not needing multiple copies of the expression.
This technique could be used to further simplify the …
> Abstracting REG and RSV terms for therm-commit ramp

- src/multi_stage/dual_dynamic_programming.jl
y in keys(EP_cur[c]) is a DenseAxisArray key, to extract the index we need to have y[1], as already done also on line 350 in function fix_capacity_tracking.
> Fix typo in fix_initial_investments

- src/model/policies/cap_reserve_margin.jl
CapResPeriodLength is not implemented now.
No need for a warning.
> Remove scary warning about CapResPeriodLength

- src/case_runners/case_runner.jl
- src/write_outputs/write_outputs.jl
Because of the new default settings, the first term in these expression always evaluates to false. They can be removed.
> Remove superfluous call to `haskey`

- src/configure_settings/configure_settings.jl
Not overwriting results (0) is the typical setting in the examples.
...
This is something I should have included with #431.
> Add default for OverwriteResults key

- docs/make.jl
- docs/src/data_documentation.md
Doc page upgrade: moving the input output before additional tools, fleshing out the multistage, getting rid of/adding content to the missing content in doc pages.
Better integrating multi-stage expansion instructions (there should be more clarity about the three ways to run GenX: single stage, multi-stage myopic, and multi-stage foresight with discussion on what that means for computational performance and how input files change for each mode)
> Update make.jl to update the documentation pages for GenX v0.3.5

- docs/src/slack_variables_overview.md
bare `$` as in $/MWh should be written as `\$`. Else it's interpreted as latex.
> fix markdown typos

- src/case_runners/case_runner.jl
Within the `function run_genx_case_simple!()`, the `AbstractString` `case` is assigned to a newly introduced variable `inputs_path`. But, this is not necessary any more (maybe its presence is primarily a historic relic from the ancestral `GenX.jl`). This PR attempts to get rid of that and by doing so, makes the coding style logically consistent, connected, and in tune with the rest of the code.
> Update case_runner.jl by removing unnecessary inputs_path

- CHANGELOG.md
- src/model/policies/cap_reserve_margin.jl
- src/model/policies/energy_share_requirement.jl
- src/model/policies/maximum_capacity_requirement.jl
- src/model/policies/minimum_capacity_requirement.jl
1. `vMaxCap_slack` is now subtracted from `EP[:eMaxCapRes]` (see https://github.com/GenXProject/GenX/issues/461)
2. The definition of slack variables now precedes the constraint formulation for all policy constraints
> Fixed issue #461 and bug in policy constraint slacks

- src/configure_solver/configure_highs.jl
Removes "simplex_dualise_strategy" setting which is no longer compatible with HiGHS v1.5
> Fix HiGHS solver setting error (solves Issue #489)

- CHANGELOG.md
- src/configure_solver/configure_cplex.jl
This allows CPLEX to handle the Pre_Solve key which is in many examples.
Note that 1 is the default, which is to have presolve turned on.
> Handle Pre_Solve key for CPLEX

- CHANGELOG.md
- src/model/resources/hydro/hydro_inter_period_linkage.jl
- src/model/resources/storage/long_duration_storage.jl
Use the `mod1` function to eliminate needing separate constraints for 'interior' periods and 'start' periods.
This also removes the warning that happened because `MODELED_PERIODS_INDEX[end]` was a single value rather than vector.
> Combine two LDS constraints

- CHANGELOG.md
- docs/src/data_documentation.md
- src/write_outputs/write_capacity.jl
In many studies, users wish to know the dual (shadow price) of the capacity constraint for a given resource or set of resources. This change adds this to an existing output file.
> Add output for dual of capacity constraint

- Example_Systems/MethodofMorrisExample/OneZone/Network.csv
- Example_Systems/RetrofitExample/RetrofitExample_MultiStage/Inputs/Inputs_p1/Network.csv
- Example_Systems/RetrofitExample/RetrofitExample_MultiStage/Inputs/Inputs_p2/Network.csv
- Example_Systems/RetrofitExample/RetrofitExample_MultiStage/Inputs/Inputs_p3/Network.csv
- Example_Systems/SmallNewEngland/OneZone/Network.csv
These are not needed since there's only one zone.
> Remove Network.csv files from single-zone cases

- src/write_outputs/write_costs.jl
Prevent an error when there are no resources with COMMIT in a given zone. This addresses @wrgunther 's issue, #506 .
> Fix error on write_costs re: COMMIT_ZONE #506

- src/case_runners/case_runner.jl
- src/write_outputs/write_outputs.jl
write_outputs() now returns the path where the results were saved after any changes by choose_output_dir(). This is useful when try to save other results to the same directory.
I also changed mkdir() to mkpath, to avoid errors were a parent directory of the intended results folder is missing.
Finally, I updated the mga outputs_path folder to be the folder created by  choose_output_dir(), not the original outputs_path
> Return path from write_outputs()

- .github/ISSUE_TEMPLATE/bug.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature.yml
- .github/ISSUE_TEMPLATE/question.yml
This creates templates for Bug Reports, Feature Requests, and General Questions.
See https://github.com/cfe316/GenX/issues/new/choose for an example of what it will look like.
> Feature issue template

- src/case_runners/case_runner.jl
- src/write_outputs/write_outputs.jl
write_outputs now returns the path where the results were saved after any changes by choose_output_dir()
I also changed mkdir() to mkpath, to avoid errors were a parent directory of the intended results folder is missing.
Finally, I updated the mga outputs_path folder to be the folder created by  choose_output_dir(), not the original outputs_path
> Return path from write_outputs

- .travis.yml
- README.md
These are causing the build to fail and we don't have any tests, so they were pretty pointless. Without this we can at least see if the builds succeed.
> Remove coveralls and coverage

- Example_Systems/RetrofitExample/RetrofitExample_MultiStage/README.txt
- src/load_inputs/load_generators_data.jl
The Retrofits feature is still under development, so it is being disabled. In order to re-enable the feature, remove the line from load_generators_data! which sets RETRO to be an empty Vector.
> Disable Retrofits feature

- src/model/expression_manipulation.jl
- src/model/generate_model.jl
- test/expression_manipulation_test.jl
@gmantegna identified some bugs on the develop branch after PR #498 . I had missed combinations of types in how I defined `add_similar_to_expression!()`. To fix this and try to reduce the chances of the same happening in the future, I've already:
- Abstracted the method definitions so that we don't have to explicitly define every combination. This should also hopefully reduce code maintenance requirements in the future as we use new types.
- `add_similar_to_expression()` and most of the other functions are now defined for single entry expressions as opposed to only arrays of expressions.
- `add_similar_to_expression()` is also defined for AbstractArrays, such as expressions which have indices which don't go from 1:length(array)
- `createemptyexpression()` is replaced with …
> Bug fix and simplify expression_manipulations.jl

- src/multi_stage/dual_dynamic_programming.jl
The value of `mysetup["CurrStage"]` is modified in `run_genx_case_multistage!` inside a for loop. The dictionary `mysetup` is then passed to function `run_ddp` as `setup_d` and the current stage value is used by function `initialize_cost_to_go` but it is not updated to match the current stage, and left set to the last stage as done by parent function  `run_genx_case_multistage!`. 
This commit fixes that and set the right current stage in `setup_d` before initializing the cost-to-go.
> Bug Fix for correct tracking of current investment stage by SDDP

- src/GenX.jl
"const is used to declare global variables whose values will not change. In almost all code (and particularly performance sensitive code) global variables should be declared constant in this way." 
https://docs.julialang.org/en/v1/base/base/#const
> Change ModelParameterScale to const

- src/load_inputs/load_fuels_data.jl
> Remove unneeded check in `load fuels`

- CHANGELOG.md
- docs/make.jl
- docs/src/data_documentation.md
- docs/src/maintenance.md
- src/model/resources/maintenance.jl
- src/model/resources/resources.jl
- src/model/resources/thermal/thermal.jl
- src/model/resources/thermal/thermal_commit.jl
- src/write_outputs/write_maintenance.jl
- src/write_outputs/write_outputs.jl
This adds the ability to have maintenance constraints for arbitrary generators that have
* a COMMIT-like quantity
* a eTotalCap-like quantity
* a Cap_Size-like quantity
I've implemented this in a very general way: 
* The maintenance variables are given custom names per-resource (with an optional suffix). This potentially allows for more than one component of a complex resource to have maintenance, on different schedules.
* So far I've "implemented" maintenance variables for THERM generators only.
* I plan to apply these to fusion core
This adds 4 optional columns to Generators_data.csv:
`MAINT`, `Maintenance_Duration`, `Maintenance_Frequency_Years` and `Maintenance_Begin_Cadence`.
The first is either 0/1. The others are not read for a given resource unless it has MAINT=1.
The `MAINT` …
> Maintenance constraints (and for thermal generators)

- CHANGELOG.md
- src/case_runners/case_runner.jl
- src/multi_stage/endogenous_retirement.jl
Fixed computation of cumulative minimum retirements in multistage code. Previously, minimum capacity retirement parameters were not added up and this resulted in the minimum retirement constraints enforcing wrong lower bounds ( #514 )
> Added computation of cumulative minimum capacity retirements in multistage

- CHANGELOG.md
- src/model/generate_model.jl
- src/model/resources/storage/storage_all.jl
- src/model/resources/vre_stor/vre_stor.jl
This fixes #541. 
The expression `eELOSSByZone` is accessed in `co2_cap.jl` without being initialized if no storage is present in the model. 
Run `Example_Systems/SmallNewEngland/OneZone/Run.j`. 
> Fix eELOSSByZone expr: access before initialization

- src/model/core/reserves.jl
- src/model/generate_model.jl
Divide the core Reserves functionality into
1. variable and expression creation
(space for potential modification)
2. constraint application
This makes the module more like the CapacityReserveMargin or MinCapReq policies, allowing the expressions to be modified before constraints are applied.
> Separate reserves into creation and constraints

- src/model/expression_manipulation.jl
- src/model/resources/curtailable_variable_renewable/curtailable_variable_renewable.jl
- src/model/resources/hydro/hydro_res.jl
- src/model/resources/storage/storage_all.jl
- src/model/resources/storage/storage_asymmetric.jl
- src/model/resources/storage/storage_symmetric.jl
- src/model/resources/thermal/thermal_commit.jl
- src/model/resources/thermal/thermal_no_commit.jl
- test/expression_manipulation_test.jl
This doesn't quite compile yet for technical reasons related to `add_similar_to_expression!`.
I tried refactoring some of the reserve formulations in order to better understand how they should work for fusion, and I think others might appreciate the simplifications.
> Refactor reserves

- src/write_outputs/write_maintenance.jl
This is a minor change to support my `fusion` module. This function is not used anywhere outside of the `maintenance` module.
> Allow ability to scale written timeseries outputs.

- src/write_outputs/write_charging_cost.jl
- src/write_outputs/write_energy_revenue.jl
- src/write_outputs/write_price.jl
This slightly simplifies
`write_prices.jl`
`write_charging_cost.jl`
`write_energy_revenue.jl`.
I tested this on SNE/ThreeZones and the results are identical to within numerical errors.
> Function to compute locational marginal prices from output

- src/model/resources/hydrogen/electrolyzer.jl
> Fix #567: apply min/max power for electrolyzers

- src/write_outputs/capacity_reserve_margin/write_capacity_value.jl
This is a refactor for enhanced readability.
This should help me add fusion in a subsequent PR.
This was tested on the VRE_STOR example and SmallNewEngland/ThreeZones (with CRM turned on). The results are identical other than some outputs which were `-0.0` are now `0.0`.
> Refactor write capactiy value

- src/write_outputs/capacity_reserve_margin/write_capacity_value.jl
This fixed a bug where cases multiple CRM zones have an error during output.
This has been tested now; the results are identical (except for -0.0 vs 0.0, like before.)
> Fix DimensionMismatch error in refactored CRM

- src/model/resources/thermal/thermal_commit.jl
- src/write_outputs/capacity_reserve_margin/effective_capacity.jl
- src/write_outputs/capacity_reserve_margin/write_capacity_value.jl
- src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
Account for the fact that THERM plants have provide no "capacity" while they are under maintenance.
> Output correct CRM values for THERM plants with maintenance

- src/configure_settings/configure_settings.jl
- src/load_inputs/load_generators_data.jl
Prevent double printing of warnings.
> use maxlog=1

- Example_Systems/RealSystemExample/ISONE_Trizone/Network.csv
- Example_Systems/RealSystemExample/ISONE_Trizone_FullTimeseries/Network.csv
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Inputs/Inputs_p1/Network.csv
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Inputs/Inputs_p2/Network.csv
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Inputs/Inputs_p3/Network.csv
- Example_Systems/RealSystemExample/MGA_ISONE_Trizone_FullTimeseries/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Inputs/Inputs_p1/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Inputs/Inputs_p2/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Inputs/Inputs_p3/Network.csv
- Example_Systems/SmallNewEngland/ThreeZones_Slack_Variables_Example/Network.csv
- Example_Systems/VREStor_Example/Network.csv
- docs/src/data_documentation.md
- docs/src/model_notation.md
- src/load_inputs/load_network_data.jl
- test/ThreeZones/Network.csv
- test/VREStor/Network.csv
This changes the preferred Network input format from a matrix of 1, 0, -1 to lists of Start_Node, End_Node.
* This may not be perfect: here we use Node, which a more technical term, but in other places in the code and docs we largely use "Zone".
> Prefer columns-style network format to matrix format

- src/write_outputs/energy_share_requirement/write_esr_revenue.jl
- src/write_outputs/write_net_revenue.jl
Refactor `write_esr_revenue.jl` to make it easier to add FUSION in the near future.
Mostly renaming variables, breaking up a long line, and giving a consistent name for multiple accesses.
Run any case. I tested this on a simple case with two ESR zones. The output is identical.
> Minor refactor of write_esr_revenue

- CHANGELOG.md
- src/write_outputs/reserves/write_rsv.jl
This fixes #575.
* This also fixes the scale of the outputs in the Total column.
* This was tested on the SmallNewEngland/ThreeZones case and it fixes the unmet reserves column and correctly scales the Total column.
> Correctly write and scale unmet reserve output

- src/write_outputs/min_max_capacity_requirement/write_maximum_capacity_requirement.jl
- src/write_outputs/min_max_capacity_requirement/write_minimum_capacity_requirement.jl
This makes the code write_min_capacity and write_max_capacity symmetrical. This is a minor step toward separating the 'currency scale' and 'energy scale'.
- [n/a] Code changes are sufficiently documented; i.e. new functions contain docstrings and .md files under /docs/src have been updated if necessary.
- [n/a] CHANGELOG.md has been updated (if this is a 'notable' change).
Tested on RealSystemExample/ISONE_Trizone after creating a MaxCapReq entry. The results are bit-for-bit identical.
> Use scale_factor in write_min/max_capacity_requirement.jl

- .github/workflows/ci.yml
This updates the list of Julia versions in the ci.yml file and removes the tests on Julia nightly, as they are not allowed to fail. Reference: https://github.com/actions/runner/issues/2347
> Update Julia versions in ci.yml

- src/write_outputs/capacity_reserve_margin/write_capacity_value.jl
> Fix #584: derating factor for VRE_STOR in write_capacity_value

- CHANGELOG.md
- src/model/resources/hydro/hydro_inter_period_linkage.jl
- src/model/resources/hydro/hydro_res.jl
1. Modified constraint `cHydroReservoir` in _hydro_res.jl_ so that it applies only to interior time steps (those that are not at the start of a subperiod). 
2. Added a constraint that applies the storage constraint linking first and last time step of each subperiod only for short duration hydro reservoirs.
3. Renamed constraints in _hydro_inter_period_linkage.jl_ so that the naming is consistent with other long duration storage constraints.
> Fixed #572 : allow long duration hydro reservoir

- CHANGELOG.md
- src/write_outputs/transmission/write_transmission_losses.jl
This PR fixes #616.
Transmission losses due to power flows are now scaled only once.
> Fix scaling of tx losses in tlosses.csv #616

- src/write_outputs/write_costs.jl
This PR addresses the first part of issue #553.
The "Total" column of the "cTotal" row of `costs.csv` is now equal to `value(EP[:eObj])` instead of the model objective function. This ensures that `costs.csv` contains the total cost even when the objective function changes (e.g., in MGA).
> Fix cTotal on write_costs: #553

- CHANGELOG.md
- Example_Systems/VREStor_Example/Settings/genx_settings.yml
- docs/src/data_documentation.md
- src/configure_settings/configure_settings.jl
- src/load_inputs/load_inputs.jl
- src/model/resources/storage/storage_all.jl
- src/model/resources/vre_stor/vre_stor.jl
- test/test_VREStor.jl
This PR minimizes the stray effect of virtual charging and discharging costs in storage_all.jl (Since virtual operations are theoretical and often lead to absurd outcomes). 
Issue numbers fixed: Fixes Issue #604 
Updated the test settings files by incorporating new settings parameter and modified objective function value for successful tests
> Get rid of costs to virtual charging & discharging in storage_all.jl

- CHANGELOG.md
- src/model/resources/hydro/hydro_inter_period_linkage.jl
- src/model/resources/hydro/hydro_res.jl
> Revert "Fixed #572 : allow long duration hydro reservoir"

- CHANGELOG.md
- src/multi_stage/dual_dynamic_programming.jl
Fixing bug in function `fix_initial_investments`, introduced by https://github.com/GenXProject/GenX/pull/326 . The aim of this PR was to set the initial capacity at stage t using the available capacity in stage t-1 only for generators whose indices are in `RET_CAP`.
However, `fix_initial_investments` does not consider only generators, but also transmission lines. So if the index of a given transmission line does not happen to be in `RET_CAP`, the available capacity of that transmission line at stage t-1 will not be carried over to stage t.
As a result of this bug, GenX believes that it has not built any transmission capacity in previous stages for those lines whose indices are not in `RET_CAP`, and so in every stage after the first one GenX will build a lot more transmission capacity than …
> Fix update of starting transmission capacity in multistage GenX

- CHANGELOG.md
- docs/src/data_documentation.md
- src/configure_settings/configure_settings.jl
- src/model/resources/storage/storage.jl
- src/model/resources/vre_stor/vre_stor.jl
This PR adds a setting and accompanying feature to turn off the storage virtual charge/discharge functionality if desired by the user.
Note that this PR does not remove the decision variables for virtual charging and discharging; it only removes them from the CRM constraint itself, so they are forced to zero by the optimization as they have an associated cost. I designed this PR this way for the sake of code simplicity, as this is a feature that is not expected to be used regularly (so I don't think that the increased computational efficiency that would come from removing the variables from the optimization entirely is worth the increased code complexity).
I also did this myself, but if you run the SmallNewEngland case with the new "StorageVirtualDischarge" setting set to 0, you will see …
> Add a setting to turn off storage virtual discharge

- src/load_inputs/load_resources_data.jl
This fixes the set `ret_cap_charge` (or `inputs["RET_CAP_CHARGE"]`), which consists of the indices of resources with `Can_Retire = 1` and `existing_charge_cap_mw >= 0`
> Fix ret_cap_charge in load_resources

- CHANGELOG.md
- src/model/solve_model.jl
- src/write_outputs/write_outputs.jl
`write_status` looks for the `objective_bound` of the model, which might not exist (for example, HiGHS only implements the objective bound for MIPs).
This fix addresses the issue with `write_outputs` when `UCommit = WriteShadowPrices = 1` by moving the linearization and re-optimization of the model immediately after `write_status` is called.
> Fix write_status with UCommit=1 and Shadow Prices

- README.md
- docs/make.jl
Changed the URL to GenX.jl for doc rendering
> Changed deploydoc URL to GenX.jl

- README.md
- docs/make.jl
Pull up develop to sync with main and release branch (Changed the URL to GenX.jl for doc rendering)
> Sync up develop (Changed deploydoc URL to GenX.jl)

- src/multi_stage/dual_dynamic_programming.jl
This updates the docstring for the [initialize_cost_to_go](https://github.com/GenXProject/GenX.jl/blob/5100d174b17357cd054a4234dcfeeaeadea58e1a/src/multi_stage/dual_dynamic_programming.jl#L602) function and adjusts the formula for the discount factor to reflect the code implementation, potentially resolving issue #671.
> Fix initialize_cost_to_go docstring

- CHANGELOG.md
- src/multi_stage/write_multi_stage_costs.jl
Add discount with OPEX multipliers  to `cUnmetPolicyPenalty` in [write_multi_stage_cost.jl](https://github.com/GenXProject/GenX.jl/blob/5100d174b17357cd054a4234dcfeeaeadea58e1a/src/multi_stage/write_multi_stage_costs.jl#L40).
This should fix #623.
#623 
Tested on the multistage example. 
> Discount cUnmetPolicyPenalty in write_multi_stage_cost.jl

- CHANGELOG.md
- docs/src/User_Guide/generate_alternatives.md
- src/additional_tools/modeling_to_generate_alternatives.jl
- src/case_runners/case_runner.jl
- src/configure_settings/configure_settings.jl
- src/model/generate_model.jl
This PR fixes a constraint in the mga algorithm to compute total capacity in each zone from a given technology type.
This has been tested using a MGA_ISONE_Trizone system with TDR on and 1848 hours.
> Mga fix/0.4.0

- CHANGELOG.md
- src/model/core/operational_reserves.jl
This PR fixes the docstring of [operational_reserves_contingency!](https://github.com/GenXProject/GenX.jl/blob/5100d174b17357cd054a4234dcfeeaeadea58e1a/src/model/core/operational_reserves.jl#L23-L69) function in `operational_reserves.jl`.
Addresses #689
Issue #689.
> Fix docstring in operational_reserves.jl

- .github/workflows/documentation.yml
- CHANGELOG.md
- Project.toml
- docs/make.jl
This PR updates the `devbranch` in the `make.jl` file of the docs to track the develop branch instead of the main branch.
> Allow dev docs to track develop branch

- .github/workflows/PR_checks.yml
- .github/workflows/ci.yml
- .github/workflows/test_examples.yml
- CHANGELOG.md
- Project.toml
This PR adds a new GitHub workflow/action to remind the author to update the CHANGELOG.md file and version number when a PR targeting develop is opened. If the 'Skip-Changelog' label is added to the PR, the first check will be skipped.
> Add workflow to check PR, update existing workflows

- CHANGELOG.md
- Project.toml
- src/GenX.jl
- src/case_runners/case_runner.jl
- src/configure_settings/configure_settings.jl
- src/startup/genx_startup.jl
- src/write_outputs/write_outputs.jl
This PR adds two new functions to the codebase:
- `print_genx_version()` that prints the version of GenX to the console when loading GenX. 
- `write_system_env_summary()` that writes a summary of the current testing environment to a YAML file. 
This information can be helpful for reproducing and analyzing test results.
It addresses issue #708.
By running the example cases. 
> Print version at startup and export it to disk

- CHANGELOG.md
- Project.toml
- docs/src/User_Guide/multi_stage_input.md
- example_systems/6_three_zones_w_multistage/settings/multi_stage_settings.yml
- src/case_runners/case_runner.jl
- src/configure_settings/configure_settings.jl
- src/multi_stage/dual_dynamic_programming.jl
- test/test_multistage.jl
This PR adds in an additional step in run_ddp where the outputs are saved after each iteration of a multistage run. It does so through the use of a new key in multistage settings called WriteIntermittentOutputs, and uses the function write_outputs().
This PR changes the files dual_dynamic_programming.jl (run_ddp()) and case_runner.jl (run_genx_multistage). It merges into the branch configure_multistage_settings because it needs the default key for WriteIntermittentOutputs in configure_multistage_settings.
Issue #658 
This can be tested by adding a key in multistage_settings.yml in example 6 to WriteIntermittentOutputs: 1, then running example 6 as usual and observing that all outputs are occurring as expected after each iteration of the run. Testing was done to ensure that everything is …
> 658 save resource buildout every few optimizer iterations and allow optimizer warm start

- CHANGELOG.md
- Project.toml
- src/time_domain_reduction/time_domain_reduction.jl
Fix TDR to load `Fuels_data.csv` even without a `None` column. 
Addresses #552 
By running any example case with `TimeDomainReduction: 1` and without a `None` column in the `Fuels_data.csv` input file.
> Make None colum in Fuels_data optional

- Project.toml
- example_systems/2_three_zones_w_electrolyzer/resources/Thermal.csv
- example_systems/6_three_zones_w_multistage/inputs/inputs_p1/resources/Thermal.csv
- example_systems/6_three_zones_w_multistage/inputs/inputs_p2/resources/Thermal.csv
- example_systems/6_three_zones_w_multistage/inputs/inputs_p3/resources/Thermal.csv
Remove `Hydro_Energy_to_Power_Ratio` column from `thermal.csv` files in two example_systems.
Fixes #737
n/a
> Remove bogus Hydro_* columns in examples

- CHANGELOG.md
- Project.toml
- src/model/resources/resources.jl
This PR fixes the default value of the `cap_size` function in the resource interface.
> Fix default value of cap size api

- Project.toml
- docs/src/Tutorials/Tutorial_2_network_visualization.md
- docs/src/User_Guide/model_input.md
This PR updates the documentation for the GenX inputs and clarifies that the `Network.csv` file is not required if running a single-zone model.
Related to #705.
> Update docs for `Network.csv`

- Project.toml
- src/GenX.jl
simple_operation does not exist, so don't `export` it.
This `export` related to the development of automated tests and no longer exists within the project.
#739 
Observe that automated tests pass.
> Remove invalid package export

- CHANGELOG.md
- Project.toml
- docs/src/User_Guide/model_configuration.md
- src/case_runners/case_runner.jl
- src/configure_solver/configure_solver.jl
This PR allows for the use of the Gurobi.Optimizer with multistage models.
When running a multistage model with a "single use" Gurobi license like:
```julia
using GenX
using Gurobi
run_genx_case!(dirname(@__FILE__), Gurobi.Optimizer)
```
one will get
```julia
ERROR: LoadError: Gurobi Error 10009: Single-use license. Another Gurobi process with pid 12345 running.
```
[The solution](https://github.com/jump-dev/Gurobi.jl?tab=readme-ov-file#reusing-the-same-gurobi-environment-for-multiple-solves) looks like:
```julia
using GenX
using Gurobi
if !(@isdefined GRB_ENV)  # the whole point is to only create GRB_ENV once per Julia session
const GRB_ENV = Gurobi.Env()
end
run_genx_case!(dirname(@__FILE__), () -> Gurobi.Optimizer(GRB_ENV))
```
see examples above
> support reuse of Gurobi environment for multistage models

- CHANGELOG.md
- Project.toml
- src/model/resources/vre_stor/vre_stor.jl
Can be tested with the original VRE_STOR example case
> Charge constr vrestor

- CHANGELOG.md
- Project.toml
- src/case_runners/case_runner.jl
- src/load_inputs/load_resources_data.jl
- src/model/resources/resources.jl
- src/startup/genx_startup.jl
- src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
- src/write_outputs/energy_share_requirement/write_esr_revenue.jl
- src/write_outputs/write_curtailment.jl
- src/write_outputs/write_net_revenue.jl
- src/write_outputs/write_subsidy_revenue.jl
- src/write_outputs/write_vre_stor.jl
This PR resolves the `UndefRefError: access to undefined reference` error encountered when running GenX with the recently released Julia v1.11. Specifically, Julia v1.11 introduced a new interface for vectors, and this PR updates the `getproperty` function for `Vector{GenXResources}` to ensure compatibility.
This should fix the CI with Julia 1.11. 
It can be tested by running any of the examples with Julia 1.11. 
> Fix getproperty for `Vector{Resources}` to align with new array interface

- Project.toml
- docs/src/Tutorials/Tutorial_1_configuring_settings.md
Addresses #786: Set `TimeDomainReduction` parameter to 1 to enable TDR.
Fixes #786 
By reviewing the `Tutorial_1_configuring_settings` page inside the `Tutorial` folder of the documentation.
> Fix description of TDR setting parameters in Tutorial 1

- CHANGELOG.md
- Project.toml
- src/model/core/operational_reserves.jl
- src/model/expression_manipulation.jl
- test/expression_manipulation_test.jl
Addresses #778 by adding a new version of `add_similar_to_expression!` in `expression_manipulation.jl`, which handles expressions that are `Arrays` rather than `GenericAffExpr`. This implementation performs an elementwise sum of the two arrays, similar to the behavior of the `+` operator in `EP[:expr1] = EP[:expr1] + EP[:expr2]` when `expr*` are vectors.
#778.
As the Issue description suggests, this can be replicated with the `5_three_zones_w_piecewise_fuel` example case by entering 2000 for the `Static_Contingency_MW`. 
> Add add_similar_to_expression! for arrays

- CHANGELOG.md
- Project.toml
- docs/src/Tutorials/Tutorial_4_model_generation.md
- docs/src/User_Guide/model_configuration.md
- example_systems/3_three_zones_w_co2_capture/resources/Storage.csv
- example_systems/3_three_zones_w_co2_capture/settings/genx_settings.yml
- src/configure_settings/configure_settings.jl
- src/model/generate_model.jl
- src/model/resources/hydro/hydro_inter_period_linkage.jl
- src/model/resources/storage/long_duration_storage.jl
This PR introduces a new settings flag to provide flexibility in activating new long-duration storage constraints (PR #781).
Using the "3_three_zones_w_co2_capture" example case and enabling LDS on storage resources.
> Settings flag for new LDS constraints activation

- CHANGELOG.md
- src/write_outputs/write_costs.jl
This PR addresses #804 by adding the expression `eTotalCMaxCapSlack` to the `cUnmetPolicyPenalty` column in the `costs.csv` file.
Fixes #804.
Using the `example_systems/4_three_zones_w_policies_slack` example. 
> Add `eTotalCMaxCapSlack` to `cUnmetPolicyPenalty` in `write_costs.jl`

- CHANGELOG.md
- Project.toml
- src/model/core/fuel.jl
- src/model/resources/thermal/thermal.jl
Update thermal.jl with links to fuels page for Piecewise linear cost
This PR creates links from the Thermal page to the fuels page for piecewise linear cost curve
This PR creates links from the Thermal page to the fuels page for piecewise linear cost curve
> Update thermal.jl with links to fuels page for Piecewise linear cost

- Project.toml
- src/model/resources/storage/investment_charge.jl
- src/model/resources/storage/investment_energy.jl
- src/model/resources/storage/long_duration_storage.jl
- src/model/resources/storage/storage.jl
- src/model/resources/storage/storage_all.jl
- src/model/resources/storage/storage_asymmetric.jl
- src/model/resources/storage/storage_symmetric.jl
Lightly clean up the syntax and some logic in the storage model. This 
n/a
Strictly internal change. Should test symmetric, asymmetric, and LDS.
> Clean up storage model syntax, logic
