- README.md
- docs/src/model_notation.md
> Fixed typos

- src/model/resources/flexible_demand/flexible_demand.jl
> Remove debugging info from flexible demand module

- src/write_outputs/transmission/write_transmission_flows.jl
- src/write_outputs/write_outputs.jl
This is to fix a bug I introduced which was recently pulled to `main`. 
This addresses #122 (Normally I would submit directly to dev).
> Fix bug on main which prevents writing many outputs

- src/write_outputs/capacity_reserve_margin/write_capacity_value.jl
- src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
- src/write_outputs/reserves/write_reg.jl
- src/write_outputs/reserves/write_rsv.jl
- src/write_outputs/transmission/write_transmission_flows.jl
- src/write_outputs/transmission/write_transmission_losses.jl
- src/write_outputs/ucommit/write_commit.jl
- src/write_outputs/ucommit/write_shutdown.jl
- src/write_outputs/ucommit/write_start.jl
- src/write_outputs/write_charge.jl
- src/write_outputs/write_curtailment.jl
- src/write_outputs/write_nse.jl
- src/write_outputs/write_outputs.jl
- src/write_outputs/write_power.jl
- src/write_outputs/write_power_balance.jl
- src/write_outputs/write_storage.jl
- src/write_outputs/write_subsidy_revenue.jl
This is "part 1" of a series of commits that vectorize the writing procedures. This work was originally done by @xuqingyu on his `Dev_FC_QX` branch, but seems too valuable to wait until that whole branch can be merged in. I've pulled out changes to these files in the `write_outputs/` directory:
```
transmission/write_transmission_flows.jl
transmission/write_transmission_losses.jl
reserves/write_reg.jl
reserves/write_rsv.jl
ucommit/write_shutdown.jl
ucommit/write_commit.jl
ucommit/write_start.jl
capacity_reserve_margin/write_capacity_value.jl
capacity_reserve_margin/write_reserve_margin.jl
write_charge.jl
write_curtailment.jl
write_nse.jl
write_power.jl
write_power_balance.jl
write_storage.jl
write_subsidy_revenue.jl
```
All these files are relatively easy to change, as they can be done …
> Vectorize the simpler writing procedures

- src/model/resources/storage/storage_all.jl
- src/write_outputs/write_storagedual.jl
I should have included this in my last PR as this file does not require modifying other files in order to be vectorized. However, it required a bit of debugging so I left it out. I've now checked it; it should provide an output identical to that of the non-vectorized code.
> Vectorize write_storagedual

- src/write_outputs/write_costs.jl
This is a single-file solution for speeding up write_costs, which for my systems is the most expensive writing procedure. On a very small test system it sped up the write time from 3s to 0.08s, so I'm looking forward to trying it out on my system where write_cost took 8200s previously.
This PR is separate but complimentary to #137 and #139. While it's the simplest, it's probably the most important of the three.
> Vectorize write_costs

- src/write_outputs/capacity_reserve_margin/write_capacity_value.jl
- src/write_outputs/capacity_reserve_margin/write_reserve_margin_revenue.jl
- src/write_outputs/energy_share_requirement/write_esr_prices.jl
- src/write_outputs/reserves/write_reg.jl
- src/write_outputs/reserves/write_rsv.jl
- src/write_outputs/transmission/write_nw_expansion.jl
- src/write_outputs/transmission/write_transmission_flows.jl
- src/write_outputs/transmission/write_transmission_losses.jl
- src/write_outputs/ucommit/write_commit.jl
- src/write_outputs/ucommit/write_shutdown.jl
- src/write_outputs/ucommit/write_start.jl
- src/write_outputs/write_charge.jl
- src/write_outputs/write_charging_cost.jl
- src/write_outputs/write_costs.jl
- src/write_outputs/write_curtailment.jl
- src/write_outputs/write_emissions.jl
- src/write_outputs/write_energy_revenue.jl
- src/write_outputs/write_net_revenue.jl
- src/write_outputs/write_nse.jl
- src/write_outputs/write_outputs.jl
- src/write_outputs/write_power.jl
- src/write_outputs/write_power_balance.jl
- src/write_outputs/write_storage.jl
- src/write_outputs/write_storagedual.jl
- src/write_outputs/write_subsidy_revenue.jl
This PR is a combination of #137, #139 ,  #145 , #147 , and #155, but target at `main` instead of `Dev` and combined into one commit to keep the history cleaner.
Co-authored-by: Qingyu Xu <xuqingyu0610@gmail.com>
> Vectorize writing of outputs

- src/write_outputs/write_outputs.jl
> Fix mismatched arguments in write_outputs

- src/load_inputs/load_generators_data.jl
This is important for running very small test systems.
> Scale all generator Cap_Size, not just those with > 1 MW

- src/load_inputs/load_period_map.jl
This is more DRY; the functionality is identical.
> Simplify load_period_map

- Example_Systems/MethodofMorrisExample/OneZone/Network.csv
- Example_Systems/SmallNewEngland/OneZone/Network.csv
Remove the column from the two examples where it was listed in `Network.csv`.
> Remove extraneous column Line_Min_Flow_MW

- docs/make.jl
Updated the devbranch to "main" instead of nothing
> Modify devbranch in make.jl

- docs/make.jl
Deleted some default keys, which aren't necessary and can cause erors
> deleted default feys from deploydocs

- docs/make.jl
Deleted the repo and branch unnecessary default lines of deploydocs
> Modified make.jl

- src/GenX.jl
- src/write_outputs/write_capacityfactor.jl
- src/write_outputs/write_outputs.jl
This branch add capacity factor calculation for non-storage generations
> Add write capacity factor function

- Example_Systems/MethodofMorrisExample/OneZone/Settings/genx_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Settings/genx_settings.yml
- Example_Systems/RetrofitExample/RetrofitExample_MultiStage/Settings/genx_settings.yml
- Example_Systems/SmallNewEngland/OneZone_MultiStage/Settings/genx_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Settings/genx_settings.yml
Added ModelingToGenerateAlternativeIterations flag to GenX_settings.yml and set it to 3 arbitrarily. Tested with Julia 1.6.x, 1.7.x, 1.8.x, and 1.9.x
> Added the MGA iterations flag

- Project.toml
- README.md
- docs/src/how_to_run_genx.md
Contains documentation updates to README/md, doc pages, and Project.toml
> Updates to README and Documentation for patch 0.3.3

- src/model/resources/storage/storage.jl
updates documentation for storage constraints to match PR #289
> Updated documentation to go with PR #289

- src/load_inputs/load_cap_reserve_margin.jl
- src/load_inputs/load_co2_cap.jl
- src/load_inputs/load_energy_share_requirement.jl
- src/load_inputs/load_fuels_data.jl
- src/load_inputs/load_generators_data.jl
- src/load_inputs/load_generators_variability.jl
- src/load_inputs/load_inputs.jl
- src/load_inputs/load_load_data.jl
- src/load_inputs/load_minimum_capacity_requirement.jl
- src/load_inputs/load_network_data.jl
- src/load_inputs/load_period_map.jl
- src/load_inputs/load_reserves.jl
Increase brevity, decrease duplication in the data loading routines. This should not change any behavior.
> Refactor loading

- docs/src/load_inputs.md
For updating the doc pages by incorporating the doc-string from the newly created load_dataframe.jl
> Updated load_inputs.md

- src/load_inputs/load_fuels_data.jl
- src/load_inputs/load_generators_variability.jl
A column called "None" will be automatically added in memory if it is not listed in Fuels_data.csv.
Columns of all 1.0's will be added for "non-variable" generators if they are not listed in Generators_variability.csv.
> Variability feature

- src/load_inputs/load_dataframe.jl
This does not fix #308 but makes the issue visible: it warns users (with @error) if there is a problem.
Arguably we should stop on @error or we should downgrade to @warn, but right now the code just continues.
> Add a function to check for duplicate keys in df

- src/additional_tools/modeling_to_generate_alternatives.jl
Corrected author name to Berntsent and Trutnevyte
> Corrected citation author name on MGA doc pages

- docs/src/core.md
- docs/src/methods.md
Within methods, it fixes broken documentation for `write_capacity_multi_stage.jl`, `transmission_multi_stage.jl`, `storage_multi_stage.jl`, `investment_multi_stage.jl`, `configure_multi_stage_inputs.jl`, and in core, if fixes documentation for `emissions.jl`
> Fixing broken documentation for methods and core

- src/write_outputs/write_capacityfactor.jl
- src/write_outputs/write_charge.jl
- src/write_outputs/write_curtailment.jl
- src/write_outputs/write_emissions.jl
- src/write_outputs/write_nse.jl
- src/write_outputs/write_price.jl
- src/write_outputs/write_reliability.jl
These changes are mostly combining near-doubled code paths from an `if setup["ParameterScale"] == 1` block.
> Clean up some output functions

- src/configure_solver/configure_highs.jl
Instead of true/false according to new HiGHS+JuMP interface rule
> Changed crossover value to on/off

- src/configure_settings/configure_settings.jl
> Added CapResPeriodLength to configure_settings.jl

- Example_Systems/MethodofMorrisExample/OneZone/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Singlezone/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone/Settings/genx_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone_FullTimeseries/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/MGA_ISONE_Trizone_FullTimeseries/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/OneZone/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/OneZone_3VREBin/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/OneZone_MultiStage/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Settings/highs_settings.yml
This turns run_crossover to a string.
> Update highs settings for examples

- src/load_inputs/load_generators_data.jl
Generally shorten the code, make it clearer, use better conventions
> Refactor load_generators_data

- Project.toml
GenX version modifications and doc page modifications
> Doc page Modifications and versions

- src/load_inputs/load_inputs.jl
> Fix #361 : allow HYDRO to use the LDS tag

- Example_Systems/SmallNewEngland/OneZone/Settings/genx_settings.yml
> Updated Commit to 2 for OneZone System

- README.md
- docs/src/how_to_run_genx.md
This should fix #330. (There are multiple flavors of markdown and markdown processors. This fixes the issue in one used by firefox on my own system, hopefully it fixes it for github as well.)
> Fix doc numbering

- src/write_outputs/write_costs.jl
Corrected to dfCost[!,Symbol("Total")] = [value(EP[:eObj]), cFix, cVar, value(EP[:eTotalCNSE]), 0.0, 0.0, 0.0] for correct cost output specifically for MGA
> Objective cost writing corrected

- src/write_outputs/reserves/write_reg.jl
- src/write_outputs/reserves/write_rsv.jl
By multiplying by the ModelScalingFactor
> Correcting the Reg and Reserve results

- Example_Systems/MethodofMorrisExample/OneZone/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Singlezone/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone_FullTimeseries/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/ISONE_Trizone_MultiStage/Settings/highs_settings.yml
- Example_Systems/RealSystemExample/MGA_ISONE_Trizone_FullTimeseries/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/OneZone/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/OneZone_3VREBin/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/OneZone_MultiStage/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones_MultiStage/Settings/highs_settings.yml
- Example_Systems/SmallNewEngland/ThreeZones_Slack_Variables_Example/Settings/highs_settings.yml
on/off instead of true/false. The run_crossover in HiGHS is no longer Boolean.
> Update the HiGHS run_crossover to string

- docs/src/how_to_run_genx.md
Add documentation for `run_genx_case!` and `run_timedomainreduction!`.
> Add instructions for new methods of running GenX

- README.md
> Remove doubled heading in README.md

- src/model/core/emissions.jl
Added missing parenthesis for emissions module log
> Fix typo in logs

- src/model/core/reserves.jl
Currently the model will throw an error if modeling just one type of reserve in the reserve module. This PR fixes this bug.
- [] Code changes are sufficiently documented; i.e. new functions contain docstrings and .md files under /docs/src have been updated if necessary.
- [] CHANGELOG.md has been updated (if this is a 'notable' change).
> Fix bug in reserves

- CHANGELOG.md
- docs/src/data_documentation.md
- src/multi_stage/configure_multi_stage_inputs.jl
Fix a column name in Generators_data to align with example cases. Assuming this is a typo that was introduced at some point.
> Fix Fixed_OM_Cost_Charge_per_MWyr to align with example cases

- Example_Systems/Electrolyzer_Example/Settings/genx_settings.yml
> Remove doubled hydrogen settings in example

- src/write_outputs/write_power_balance.jl
* Note that this doesn't get a CHANGELOG entry because electrolyzers are only added in this release.
> Fix 559; report electrolyzer power per-zone

- src/write_outputs/write_net_revenue.jl
This fixes the issues #485 and #571 .
> Fix-485: Account for Inv_Cost_Charge and Fixed_OM_Cost_Charge for STOR=2, in NetRevenue.csv

- test/resource_test.jl
- test/test_VREStor.jl
- test/test_electrolyzer.jl
- test/test_multistage.jl
- test/test_piecewisefuel_CO2.jl
- test/test_threezones.jl
- test/test_time_domain_reduction.jl
- test/utilities.jl
This PR removes the default settings from the test cases and implements minor fixes.
> Add default settings to tests and cleanup

- src/write_outputs/write_net_revenue.jl
- src/write_outputs/write_outputs.jl
This fixes write_net_revenue.jl and write_outputs.jl when Reserves = 0
> Fix write_net_revenue when Reserves = 0

- src/write_outputs/reserves/write_rsv.jl
This fixes a bug in the `write_rsv.jl`.
> Fix write_rsv.jl

- example_systems/2_three_zones_w_electrolyzer/policies/CO2_cap.csv
- example_systems/2_three_zones_w_electrolyzer/policies/Minimum_capacity_requirement.csv
- src/load_inputs/load_resources_data.jl
- src/model/resources/resources.jl
- src/model/utility.jl
- src/multi_stage/configure_multi_stage_inputs.jl
This pull request serves as a review ahead of the upcoming release. It includes the following updates:
- Reintroduce the `policy` folder for the `2_three_zones_w_electrolyzer`example, ensuring consistency across examples.
- Update the `min/max_cap` interface functions and `configure_multi_stage_inputs` for `VreStorage`.
- Make minor adjustments to maintain alignment with the existing implementation and preserve continuity.
> Update interface vre_stor. Review load data. 

- .zenodo.json
> Added zenodo author list

- src/multi_stage/endogenous_retirement.jl
Added the constraint equation
CAUTION: Need to make sure about the notation
> Added docstring for endogenous retirement constraint

- src/model/resources/flexible_demand/flexible_demand.jl
This PR fixes the bug for FLEX resources. In addition to the maximum limit on "charge", the PR adds maximum on the "discharge" amount for FLEX based on the capacity and load shifting efficiency
Tested with the WECC system
> Add FLEX power constraint

- CHANGELOG.md
- src/write_outputs/write_power_balance.jl
write_power_balance.jl previously would allow VRE_STOR to overwrite charge and discharge from STOR. After the fix, write_power_balance.jl will add two more columns for VRE_STOR to separate them from STOR.
Tested with the example system for VRE_STOR
> Fix the bug in write_power_balance.jl related to VRE_STOR

- CHANGELOG.md
- src/model/policies/energy_share_requirement.jl
Fixed the documentation in energy_share_requirement.jl to stipulate that ESR needs to be set to either 0 or 1, not >= 0 as previously stated.
Fixes Issue #468 
> Update ESR docs (Issue #468)

- Project.toml
- example_systems/1_three_zones/README.md
- example_systems/3_three_zones_w_co2_capture/README.md
- example_systems/5_three_zones_w_piecewise_fuel/README.md
Fix minor typos in paths
Fixes #715 
- [n/a] Code changes are sufficiently documented; i.e. new functions contain docstrings and .md files under /docs/src have been updated if necessary.
- [n/a] Code has been tested to ensure all functionality works as intended.
- [o] CHANGELOG.md has been updated (if this is a 'notable' change).
n/a
> Make example/README.md paths uniform; fix typos

- CHANGELOG.md
- Project.toml
- docs/src/User_Guide/model_configuration.md
This PR completes the list of settings parameters described on the `model_configuration.md` page of the documentation.
Addresses #701.
> Add all settings params to docs

- Project.toml
- src/model/core/discharge/investment_discharge.jl
- src/model/core/transmission/investment_transmission.jl
- src/model/generate_model.jl
- src/model/resources/storage/investment_charge.jl
- src/model/resources/storage/investment_energy.jl
- src/multi_stage/endogenous_retirement.jl
This removes vZERO, a JuMP variable which is always 0. This was needed in early versions of GenX due to limitations of JuMP at the time, but now it has no purpose. 
#741 
> Remove unneeded vZero variable.

- Project.toml
- src/model/core/discharge/investment_discharge.jl
- src/model/core/operational_reserves.jl
This PR attempts to fix numerous doc page rendering issues
This PR attempts to fix several doc page rendering issues that are currently there. 
> Doc rendering fix

- Project.toml
- docs/make.jl
- docs/src/Getting_Started/examples_casestudies.md
- src/startup/genx_startup.jl
Make GenX to be precompiled by default
The PR can be tested by running the following commands:
```julia
julia> using GenX
julia> include("example_systems/1_three_zones/Run.jl")
```
>  Make GenX to be precompiled by default

- CHANGELOG.md
- Project.toml
- src/model/resources/retrofits/retrofits.jl
Text added "and efficiency 𝑒𝑓𝑟 is a scalar multiplier that denotes an 'exchange rate' between capacity of the original resource and any retrofit technologies (e.g. how many MW of resource B can be sited per MW of resource A retired)." to the documentation page for retrofits
Please do not leave this blank 
This PR adds the following text at the end of the documentation page for retrofits: and efficiency 𝑒𝑓𝑟 is a scalar multiplier that denotes an 'exchange rate' between capacity of the original resource and any retrofit technologies (e.g. how many MW of resource B can be sited per MW of resource A retired).
> Update retrofits.jl documentation with additional text

- CHANGELOG.md
- CITATION.cff
- Project.toml
- README.md
- docs/src/installation.md
- src/model/resources/resources.jl
This PR updates the `develop` branch with the `release/v0.4.1` branch.
> Update develop branch with release branch

- Project.toml
- src/write_outputs/write_capacityfactor.jl
Refactor write_capacityfactor. (This was mostly done while investigating how the function works, in order to make a modification for fusion.)
This hopefully clarifies the computations that the function does.
n/a
Test examples 7 and 8; see that capacityfactor.csv is unchanged.
> Refactor write_capacityfactor.jl

- README.md
- docs/src/installation.md
This PR updates the Julia version requirements in the [README.md](https://github.com/GenXProject/GenX.jl/compare/docs/update_readme?expand=1#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5) and the [installation.md](https://github.com/GenXProject/GenX.jl/compare/docs/update_readme?expand=1#diff-0d07af81f4f5cf345a91b09fe28abbe674eb1d071f4ab4f896a9b7b65af729b0) files.
#775 
> Update Julia version requirements and recommendations

- Project.toml
- docs/src/User_Guide/generate_alternatives.md
- docs/src/User_Guide/model_configuration.md
This PR fixes the path to the MGA reference in the `model_configuration.md` page of the documentation.
Addresses #812.
By building the documentation locally. 
> Fix path to MGA reference in documentation

- CHANGELOG.md
- Project.toml
- src/write_outputs/reserves/write_rsv.jl
This PR attempts to propose better and unambiguous filenames for RSV and REG services. The current names are confusing/misleading/ambiguous
> Update write_rsv.jl with corrected filenames for RSV and REG

- CHANGELOG.md
- CITATION.cff
- Project.toml
- README.md
- docs/src/User_Guide/model_input.md
- docs/src/installation.md
This PR updates the `develop` branch with the `release/v0.4.3` branch.
> Update develop branch with `release\v0.4.3` branch 

- .github/workflows/ci.yml
- .github/workflows/test_examples.yml
- CHANGELOG.md
- CITATION.cff
- Project.toml
- README.md
- docs/src/installation.md
- src/time_domain_reduction/full_time_series_reconstruction.jl
Candidate to fix #827 . I don't have easy access to WIndows to test, though.
Fixes #827 
Try the first example with TDR and Full time domain reconstruction both turned on, on Windows.
> Fix path manipulation bug #827
